spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    profiles: local
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mySql.url}
    username: ${mySql.username}
    password: ${mySql.password}
    port: ${mySql.port}
  config:
    import: 'aws-parameterstore:'
  jpa:
    hibernate:
      ddl-auto: update  # (1) 스키마 자동 생성

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
aws:
  paramstore:
    enabled: true
    prefix: /sprig-boot-aws
    profile-separator: _
    name: danim
cloud:
  aws:
    credentials:
      access-key: ${aws.access.key}
      secret-key: ${aws.secret.key}
      instance-profile: false
    s3:
      bucket: ${bucket.name}
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false


jwt:
  secret-key: ${jwt.secret.key}
  access-token-expiration-minutes: 2880
  refresh-token-expiration-minutes: 5760